version: "3.8"

services:
  code:
    container_name: code
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: baseball
    networks:
      - hwnetwork

  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - ./:/data
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DB: baseball
    command: --secure-file-priv=""
    networks:
      - hwnetwork

networks:
  hwnetwork:
